/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_roanh_cpqkeys_algo_Nishe */

#ifndef _Included_dev_roanh_cpqkeys_algo_Nishe
#define _Included_dev_roanh_cpqkeys_algo_Nishe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_roanh_cpqkeys_algo_Nishe
 * Method:    test
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dev_roanh_cpqkeys_algo_Nishe_test
  (JNIEnv *, jclass, jint);

/*
 * Class:     dev_roanh_cpqkeys_algo_Nishe
 * Method:    computeCanon
 * Signature: ([[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_dev_roanh_cpqkeys_algo_Nishe_computeCanon
  (JNIEnv *, jclass, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
