/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_roanh_cpqkeys_algo_Traces */

#ifndef _Included_dev_roanh_cpqkeys_algo_Traces
#define _Included_dev_roanh_cpqkeys_algo_Traces
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_roanh_cpqkeys_algo_Traces
 * Method:    test
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dev_roanh_cpqkeys_algo_Traces_test
  (JNIEnv *, jclass, jint);

/*
 * Class:     dev_roanh_cpqkeys_algo_Traces
 * Method:    computeCanon
 * Signature: ([[I[I)[J
 */
JNIEXPORT jlongArray JNICALL Java_dev_roanh_cpqkeys_algo_Traces_computeCanon
  (JNIEnv *, jclass, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
