/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_roanh_cpqkeys_algo_Nauty */

#ifndef _Included_dev_roanh_cpqkeys_algo_Nauty
#define _Included_dev_roanh_cpqkeys_algo_Nauty
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_roanh_cpqkeys_algo_Nauty
 * Method:    computeCanonSparse
 * Signature: ([[I[I)[J
 */
JNIEXPORT jlongArray JNICALL Java_dev_roanh_cpqkeys_algo_Nauty_computeCanonSparse
  (JNIEnv *, jclass, jobjectArray, jintArray);

/*
 * Class:     dev_roanh_cpqkeys_algo_Nauty
 * Method:    computeCanonDense
 * Signature: ([[I[I)[J
 */
JNIEXPORT jlongArray JNICALL Java_dev_roanh_cpqkeys_algo_Nauty_computeCanonDense
  (JNIEnv *, jclass, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
