/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_roanh_cpqkeys_algo_Bliss */

#ifndef _Included_dev_roanh_cpqkeys_algo_Bliss
#define _Included_dev_roanh_cpqkeys_algo_Bliss
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_roanh_cpqkeys_algo_Bliss
 * Method:    computeCanon
 * Signature: ([I[I)[J
 */
JNIEXPORT jlongArray JNICALL Java_dev_roanh_cpqkeys_algo_Bliss_computeCanon
  (JNIEnv *, jclass, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
